name: naver_maps_flutter
description: A Flutter plugin for integrating Naver Maps in iOS and Android applications.
homepage: https://github.com/clearmaps/naver_maps_flutter/naver_maps_flutter
version: 1.0.0+21031201

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lif8201