name: naver_maps_flutter
description: A Flutter plugin for integrating Kakao Maps in iOS and Android applications.
homepage: https://github.com/clearmaps/plugins/tree/master/packages/naver_maps_flutter/naver_maps_flutter
version: 1.2.6+21063001

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2
  naver_maps_flutter_platform_interface:
    git:
      url: git://github.com/clearmaps/plugins.git
      path: packages/naver_maps_flutter/naver_maps_flutter_platform_interface
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.0
  pedantic: ^1.11.1
  plugin_platform_interface: ^2.0.0
  stream_transform: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.navermaps
        pluginClass: NaverMapsPlugin
      ios:
        pluginClass: FLTNaverMapsPlugin

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'
  flutter: ">=1.22.0"
