name: naver_maps_flutter_platform_interface
description: A common platform interface for the naver_maps_flutter plugin.
homepage: https://github.com/clearmaps/plugins
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.2.4+21062501

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0
  stream_transform: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  pedantic: ^1.10.0

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'
  flutter: ">=1.9.1+hotfix.4"
